version: 2
jobs:
  build:
    working_directory: /go/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
    docker:
      - image: golang:1.9
    steps:
      - checkout
      - run:
          name: Dependency
          command: |
            go get -u -v github.com/golang/dep/cmd/dep
            dep ensure -v
      - run:
          name: Test
          command: |
            go test -v
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              go get -u -v github.com/tcnksm/ghr
              go build -x
              VERSION=`git describe --tags --abbrev=0`
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} --replace ${VERSION} ${CIRCLE_PROJECT_REPONAME}
            else
              echo "Not master branch."
            fi
